- hosts: localhost
  connection: local
  gather_facts: False
  vars:
    # - ami_id: ami-4124d82c (paravirtual)
    # - ami_id: ami-452bd728 (hvm)
    - ami_id: ami-452bd728
    - instance_type: t2.small
    - instances: 1
    - aws_region: us-east-1
    - aws_key_name: jenkins-training-key
    - aws_group: jenkins-training-group
    - subnet_id: subnet-c9888fbf
    - vpc_id: vpc-dc3890bb
  roles:
    - aws

- hosts: "{{ hosts_group }}"
  user: ubuntu
  become: true
  gather_facts: true
  vars:
    - user: ubuntu
  roles:
    - common
    - java
    - docker
    - docker-compose
    - registry
    - node
    - cje
    - users
    - { role: preload, when: "preload is defined" }